### ISSUE TITLE
Mirror NXM uploads to Github

### ISSUE THREAD

**Issue by hyenatown** [Akatsuki2555/AsphaltRoads#1]
Yo,

This is hilariously inconvenient but I wanted to download some of your mods as of yesterday (11 Aug), but understandably, I see why you took everything down.

If you could, would you be able to release them here on Github?

**Comment by Akatsuki2555** [comment]
Alright, I'm going to do that for all mods

**Comment by hyenatown** [comment]
Oh yea, I opened the tab while they were still listed, and got an error saying "you aren't allowed to see this". It took refreshing to figure out what happened lmaoooo
